---
title: "Homework 5"
author: "Molly Martorella"
date: "11/2/2019"
output: html_document
---

```{r setup, include=FALSE}

library(tidyverse)


knitr::opts_chunk$set(
  echo = TRUE,
  fig.width = 8,
  fig.height = 6,
  out.width = "90%")

options(knitr.kable.NA = "")

theme_set(theme_bw())

```


# Problem 1

```{r}

set.seed(10)

iris_with_missing = iris %>% 
  map_df(~replace(.x, sample(1:150, 20), NA)) %>%
  mutate(Species = as.character(Species))

```

The following function, 'fix_iris':
1. fills in missing values with the mean of non-missing values for numeric columns.
2. fills in missing values with "virginica" for character columns.

```{r}

fix_iris <- function(column_to_fix){
  
  if (is.numeric(column_to_fix)) {
    
    col_mean = mean(column_to_fix, na.rm = TRUE)
    new_num_column = replace_na(column_to_fix, col_mean)
    
  } else if (is.character(column_to_fix)) {
    
    new_char_column = replace_na(column_to_fix, "virginica")
    
  } else if (!is.numeric(column_to_fix) | !is.character(column_to_fix)) {
    stop("Column vector must be numeric or character class.")
  }
  
}

```

Using a map statement to apply this function to the iris dataframe:

```{r}

map(iris_with_missing, fix_iris)

```

# Problem 2


